### ISSUE TITLE
How do I integrate themes ?

### ISSUE THREAD

**Issue by adityathebe** [AnyChart/AnyChart-NodeJS#13]

**Comment by Shestac92** [comment]
@adityathebe 
We will look into it and provide you an answer soon.

**Comment by Shestac92** [comment]
@adityathebe 
There is a possibility to use themes in AnyChart NodeJS module, but it requires some manual modifications in the AnyChart npm module. This approach is a bad practice, but it's the only way in the current version of AnyChart library. We are planning to provide an out-of-the-box theming solution in future updates. 
If you are interested in this temporary workaround, please, contact us by email - support@anychart.com
