### ISSUE TITLE
always running?

### ISSUE THREAD

**Issue by denghongcai** [AnyChart/AnyChart-NodeJS#2]
I use the example code from Quick Start, but program is always running without exit

![image](https://cloud.githubusercontent.com/assets/1433247/22915162/40c3d3ec-f2b0-11e6-817e-5c146a828cf6.png)

why?

**Comment by Rombelirk** [comment]
Hello! 

Thank you for the information.
At the moment our developer team is busy with pre-release work, we will approach this question right after the release.

Kind regards, Roman.

**Comment by Shestac92** [comment]
@denghongcai 
the AnyChart NodeJS module has been just updated. Our dev team made an effort to fix all known issues. So, we highly recommend you to update the module and please let us know if it won't solve your problem.
