### ISSUE TITLE
anychart cpu 100%

### ISSUE THREAD

**Issue by denghongcai** [AnyChart/AnyChart-NodeJS#3]
all timer ref in `anychart-bundle.min.js` should prefix by `window.` to ensure jsdom will remove all listener after `window.close()`

**Comment by Rombelirk** [comment]
Hello! 

Thank you for the information.
At the moment our developer team is busy with pre-release work, we will approach this question right after the release.

Kind regards, Roman.

**Comment by SidecoRafael** [comment]
How do you connect/use/configure image magick with anycharts? Any guides? Mine seems not working.

**Comment by Shestac92** [comment]
@denghongcai 
the AnyChart NodeJS module has been just updated. Our dev team made an effort to fix all known issues. So, we highly recommend you to update the module and please let us know if it won't solve your problem.
