### ISSUE TITLE
 AnyChart NodeJS module Prerequisite is incomplete

### ISSUE THREAD

**Issue by gluneau** [AnyChart/AnyChart-NodeJS#5]
#### Expected behavior
This message should not appear while executing code that requires this library, if you followed the install instructions.

`'Warning! Please install rsvglib utility. (https://github.com/AnyChart/AnyChart-NodeJS)'`

#### Actual behavior
As the library test to see if the prerequisite are installed with this code:
```
childProcess = spawn('rsvg-convert');
childProcess.on('error', function(err) {
  if (err.code === 'ENOENT') {
    console.warn('Warning! Please install rsvglib utility. (https://github.com/AnyChart/AnyChart-NodeJS)');
  }
});
```
It is clear that `rsvg-convert` is needed but it could not be found even after installing the repos prerequisites found [here](https://github.com/AnyChart/AnyChart-NodeJS/blob/master/README.md).

#### How to reproduce
Got the error while running @aggroed project Agx:
```
git clone git@github.com:aggroed/Agx.git
cd Agx
npm install
npm start
```

* Operating system: Ubuntu 17.10

#### Recording Of The Bug
The bug occurs even after running the install command: `apt-get install imagemagick librsvg2-dev`
 
![agx.png](https://d.pics/i/QmVoiiJKckkGqeFkHQ68p1Pzj1i3uSHwn2zTFPV1amJMfZ)

#### The Proposed fix
While they list `apt-get install imagemagick librsvg2-dev` as a prerequisite, they need one more: `librsvg2-bin`

After installing the missing package, the [Agx](https://github.com/aggroed/Agx) from @aggroed ran as expect.
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@helo/anychart-nodejs-module-prerequisite-is-incomplete">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Shestac92** [comment]
@gluneau 
Thank you for your report!
Yes, we've got the same result on fresh installed Ubuntu 17.10. We confirm that librsvg2-bin package is required too.
