### ISSUE TITLE
AnyChart and Angular 6

### ISSUE THREAD

**Issue by feeh27** [AnyChart/AnyChart-NodeJS#8]
How do I use Anychart with Angular 6?

**Comment by Shestac92** [comment]
@feeh27 
Please, check [the demo](https://github.com/anychart-integrations/anychart-angular4) of using AnyChart with Angular 4. It shows how to include AnyChart to Angular projects and use its features. 
You can update all required Angular dependencies in package.json file up to the 5th or 6th version.

**Comment by banalaarjun390** [comment]
Is there support for Anycharts for Angular 7 too?

**Comment by Shestac92** [comment]
@banalaarjun390 
The AnyChart library is compatible with Angular 7 too. For details, please, check [the demo application](http://static.anychart.com/cdn/ts/angular6Stock.zip). It's based on Angular 6, but the approach of integration AnyChart is absolutely the same for Angular 7.
